### ISSUE TITLE
使用创建备份命令，创建备份的时候， 软件使用IAM返回的URL去访问新的地址的时候，如果报文返回404，软件提示的错误信息是磁盘ID或名字不存在，而不是访问页面不存在，使用户不能正确辨析错误原因

### ISSUE THREAD

**Issue by jlsgithubname** [Huawei/OpenStackClient_VBS#1]

**Comment by IamFive** [comment]
这个行为是对的, 返回404 就是表明要访问的资源不存在, 对于客户端来说就可以认为是 要访问的 磁盘ID或者 名字不存在. 你可以试下 访问不存在的ID, 他返回的也是 404. (客户端是区分不了到底是为撒404)

----

从另一个角度讲, 客户端也不可能会预设 IAM 返回的地址是错的(整个服务都有问题了).
