### ISSUE TITLE
openstack volume backup create ext 命令的name是必选项参数，但是命令的帮助里面却是用中括号描述的 ，需要改成必选的描述

### ISSUE THREAD

**Issue by jlsgithubname** [Huawei/OpenStackClient_VBS#2]
openstack volume backup create ext 命令的name是必选项参数，但是命令的帮助里面却是用中括号描述的 ，需要改成必选的描述：

$ openstack volume backup create ext -h
usage: openstack volume backups create [-h] [--name <name>]
                                       [--description <description>]
                                       <volume>

Create new volume backup (HuaWei custom)

positional arguments:
  <volume>              Volume to backup (name or ID)

optional arguments:
  -h, --help            show this help message and exit
  --name <name>         Name of the backup
  --description <description>
                        Description of the backup

**Comment by IamFive** [comment]
Fixed

**Comment by IamFive** [comment]
另外命令已 改成了 `openstack volume backup ext create`
