### ISSUE TITLE
创建备份、恢复备份、查询任务的命令帮助的参数解释的文字写的不容易理解，需要修改

### ISSUE THREAD

**Issue by jlsgithubname** [Huawei/OpenStackClient_VBS#3]
创建备份、恢复备份、查询任务的命令帮助的参数解释的文字写的不容易理解，需要修改：
1、
root@jl-VirtualBox:/# openstack volume backup ext create -h
usage: openstack volume backup ext create [-h] [--name <name>]
                                          [--description <description>]
                                          <volume>

Create new volume backup (HuaWei custom)   --这里的备份应该是名词吧，backup是不是需要分开写（back up）

positional arguments:
  <volume>              Volume to backup (name or ID)   --需要备份的卷的名字或者ID

optional arguments:
  -h, --help            show this help message and exit
  --name <name>         Name of the backup    --这里的备份应该是名词吧，backup是不是需要分开写（back up）
  --description <description>
                        Description of the backup   --同上
2、
root@jl-VirtualBox:/# openstack volume backup job show  --os-vb-api-version=1 -h
usage: openstack volume backup job show [-h]
                                        [-f {json,shell,table,value,yaml}]
                                        [-c COLUMN] [--max-width <integer>]
                                        [--print-empty] [--noindent]
                                        [--prefix PREFIX]
                                        <job-id>

Show Job

positional arguments:
  <job-id>              job to shown  --需要显示的job的ID

optional arguments:
  -h, --help            show this help message and exit

output formatters:
  output formatter options

  -f {json,shell,table,value,yaml}, --format {json,shell,table,value,yaml}
                        the output format, defaults to table
  -c COLUMN, --column COLUMN
                        specify the column(s) to include, can be repeated

table formatter:
  --max-width <integer>
                        Maximum display width, <1 to disable. You can also use
                        the CLIFF_MAX_TERM_WIDTH environment variable, but the
                        parameter takes precedence.
  --print-empty         Print empty table if there is no data to show.

json formatter:
  --noindent            whether to disable indenting the JSON

shell formatter:
  a format a UNIX shell can parse (variable="value")

  --prefix PREFIX       add a prefix to all variable names

3、
root@jl-VirtualBox:/# openstack volume backup ext restore -h
usage: openstack volume backup ext restore [-h] <backup> <volume>

Restore volume backup

positional arguments:
  <backup>    Backup to restore (name or ID)       ---需要恢复的备份的名字或者ID
  <volume>    Volume to restore to (name or ID)   --需要恢复的备份对应的卷的名字或者ID

4、readme.rst文件需要同步修改上面的问题  和备份、恢复命令中ext字符串前移的命令举例描述

**Comment by IamFive** [comment]
1. backup 既可以是名词也可是动词～，参考原生命令 `openstack volume backup  create -h`
2. 修订成 `"job to display (ID)"`
1. 参考原生命令 `openstack volume backup  restore -h`
4. 无需改动? ext 的部分上次已经更新了.

**Comment by jlsgithubname** [comment]
readme.rst文件里面的这个描述  你没有改吗？  你下面创建命令都改了，这里为啥没改呢
1.Show Help for Create Volume Backup:
$ openstack volume backup create ext -h
usage: openstack volume backups create [-h] [--name <name>]
                                       [--description <description>]
                                       <volume>

Create new volume backup (HuaWei custom)

positional arguments:
  <volume>              Volume to backup (name or ID)

optional arguments:
  -h, --help            show this help message and exit
  --name <name>         Name of the backup
  --description <description>
                        Description of the backup

**Comment by IamFive** [comment]
看漏了。 :)

**Comment by IamFive** [comment]
已处理。
